<a href="https://colab.research.google.com/github/aashishaggarwal2000/Learning-AI-ANN/blob/main/ANN_Classification_Bank_Churn_Modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.4.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [47]:
dataset = pd.read_csv('Churn_Modelling.csv')
x=dataset.iloc[:, 3:-1].values
y=dataset.iloc[:, -1].values


In [48]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [49]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [53]:
from sklearn.preprocessing import LabelEncoder
x[:, 2]=LabelEncoder().fit_transform(x[:, 2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Label encoding of gender column is achieved using the LabelEncoder.fit_transform function that translates the binary values of the columns into 0/1.
**Note**: *The label encoder or any other transform method is always fit_transform on training data set as it calculates the mean and SD on limited data but it is only transform applied on the test data.*
**Note**: *Encoding the categorical column is important however it does introduces the unintended relatioship between the values of category. like 2>1>0 but same is not possible in the categorical values. Hence it must be used with caution.*

One Hot Encoding the "Geography" column

In [54]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
# x = np.array(ct.fit_transform(x))
# np.set_printoptions(precision=1)
# print(x)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [55]:
print(x[0:1,0:-1])

[[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1]]


### Splitting the dataset into the Training set and Test set

In [56]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [57]:
print(x_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


### Feature Scaling

In [58]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [59]:
print(x_train)
print(x_test)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]
[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


## Part 2 - Building the ANN

### Initializing the ANN

In [70]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [71]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [72]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [73]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [74]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### Training the ANN on the Training set

In [76]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3460 - accuracy: 0.8571
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3455 - accuracy: 0.8580
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3453 - accuracy: 0.8572
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3444 - accuracy: 0.8579
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3445 - accuracy: 0.8576
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3443 - accuracy: 0.8593
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3436 - accuracy: 0.8601
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3433 - accuracy: 0.8586
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3429 - accuracy: 0.8606
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3427 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [78]:
# **Homework**
# arr = np.array([[1.0, 0.0,   0.0, 600.0,   1.0,  40.0,   3.0,   60000.0,   2.0,   1.0,   1.0, 50000.0]])
# arr = sc.transform(arr)
# print(arr)
# print(ann.predict(arr))
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [85]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
# print(y_pred)
print(
    np.concatenate(
        (y_pred, y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


predict the test set and then concatenate both actual output(y_test) and predicted output(y_pred) side by side.

### Making the Confusion Matrix

In [87]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1502   93]
 [ 186  219]]


0.8605

Fetch the confution metrices and accuracy score from sk learn library and inject both the actual and predicted output. 

By definition a confusion matrix C is such that C_{i, j}
is equal to the number of observations known to be in group i and
predicted to be in group j.

Thus in binary classification, the count of true negatives is
C_{0,0}, false negatives is C_{1,0}, true positives is
C_{1,1} and false positives is C_{0,1}.