<a href="https://colab.research.google.com/github/aashishaggarwal2000/Learning-AI-ANN/blob/main/ANN_Regression_CCPP_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [36]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [37]:
tf.__version__

'2.4.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [41]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [42]:
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


The dataset would be retrieved using the pandas library and then we need to devide the full dataset into a matrix and a dependent variable vector.
Matrix would contains all the feature observations and vector would contain only the actual result column which is elctrical power generated as an output.

The matrix is being extracted using iLoc function of Pandas which allows to filter all the rows and columns based upon 2 params. We are keeping first param as empty range ":" to select all the rows and second param as the :-1 which selects column0 to second last column. 

### Splitting the dataset into the Training set and Test set

In [43]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

Here we need to split the whole dataset into training and test set. Usually it is kept at 80 to 20 ratio. Python provide us the easy way to sptil this training/test set directly from the feature matrix x and dependent variable y created above. we just need to import the train_test_split function from the sklearn.model_selection library.
Here random state is set to 0.

## Part 2 - Building the ANN

### Initializing the ANN

In [44]:
ann = tf.keras.models.Sequential() 

In order to build an artificial neural network model we need to instantiate an object of the sequenctial class from tensorflow and karas library. 
**Keras is kind of wrapper library imbedded in the tensorflow which simplifies the usage of tensorflow.

### Adding the input layer and the first hidden layer

In [45]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Here we don't need to specify the input layer as it would be automatically detected by tensorflow from the injected feature matrix. We directly define the first hidden layer with 2 params: unit = number of neural nodes we need on this layer and activation = function need to be applied on each node which is usually the rectified linear function.

### Adding the second hidden layer

In [46]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

This will be done similar to the first hidden layer added above.

### Adding the output layer

In [47]:
ann.add(tf.keras.layers.Dense(units=1))

The output layer is most important part which has only one node, so units=1. The other params like activation function is not requierd for regression ann model however we can select segmoid or soft-max functions for the binary or multiclass classification models.

## Part 3 - Training the ANN

### Compiling the ANN

In [48]:
ann.compile(optimizer='adam', loss='mean_squared_error')

When the sequential model is defined having all the layers (input, hidden and output layers). The next step is to compile the model while specifying the optimizer alogorithm='adam' which is very good for stochastic gredient decent technique of weight adjustment backpropagation and second param is loss=mse to calculate the loss function need to be optimized.

### Training the ANN model on the Training set

In [ ]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

### Predicting the results of the Test set

In [73]:
y_pred = ann.predict(x_test)
np.set_printoptions(precision=2)
print(y_pred)
y1= np.concatenate((y_test.reshape(len(y_test),1),y_pred),1) 
print(y1)

[[430.23]
 [461.34]
 [464.88]
 ...
 [472.03]
 [438.98]
 [458.13]]
[[431.23 430.23]
 [460.01 461.34]
 [461.14 464.88]
 ...
 [473.26 472.03]
 [438.   438.98]
 [463.28 458.13]]


Now comes the prediction part as our first regression artificial neural network model is ready to predict the unseen data.
For prediction we just need to pass the x_train feature set having 20% of the records splitted from orginial dataset initally.

There are cool numpy funtions which can be applied to show the predicted value with 2 digit precision.

The normal output y_prid would appear as vertical vector however we want to represent the data in the form of 2 vertical columns arranged side by side showing the actual value and predicted value.

Bit tricky as y_test vector is horizontal and we need to first reshape that 